import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./_Component/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import UserProvider from "@/UserProvider";
import CountProvider from "@/CountProvider";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./_Component/Footer/Footer";
import Marquee from "./_Component/marquee/Marquee";
config.autoAddCss = false;

const enCodeSansFont = Encode_Sans({
  subsets: ["latin"],
  weight: ["100", "400", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${enCodeSansFont.className}`}>
        <UserProvider>

          <CountProvider>
            <Marquee></Marquee>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
            <Toaster></Toaster>
          </CountProvider>
          
        </UserProvider>
      </body>
    </html>
  );
}
